### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by alyhalo** [jostorge/diffusion-hopping#3]
After running this command:

`python generate_scaffolds.py --input_molecule sample_mol.mol2 --input_protein sample_protein.pdb`

I faces with this error:

```
  File "generate_scaffolds.py", line 109
    molecules: list[Chem.Mol] = molecule_builder(final_output)
             ^
SyntaxError: invalid syntax
```

Is there a way to fix it?

I use macOS Monterey 12.1

**Comment by jostorge** [comment]
It looks like you are using an older version of Python that does not support type-hinting. Please consider using the environment provided in this repository to ensure compatibility, as explained in the README.
